spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgresql
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true